[AutoProxy 0.2.9]
||clip-studio.com
||ggpht.com
||github.com
||githubusercontent.com
||gmail.com
||google.com
||googleusercontent.com
||googlevideo.com
||googleapis.com
||gstatic.com
||gvt1.com
||pixiv.net
||pximg.net
||youtube.com
||ytimg.com
